FROM apache/airflow:3.3.0

RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir \
    pandas \
    openpyxl \
    pyodbc \
    SQLAlchemy \
    python-dotenv \
    google-cloud-bigquery \
    apache-airflow-providers-google \
    pandas-gbq